// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Claw;
/**
 *
 */
public class AutonDropCoral extends Command {

    private Claw m_claw;

    public AutonDropCoral(Claw claw) {
        m_claw = claw;
        addRequirements(m_claw);
    }


    
    @Override
    public void initialize() {
        m_claw.startMotor();
    }

    @Override
    public void end(boolean interrupted) {
       m_claw.stopMotor();
    }

    @Override
    public boolean isFinished() {
        return false;
    }

}
